# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    http_client:
        scoped_clients:
            auth.client:
                base_uri: '%env(resolve:AUTH_SERVICE_URL)%'
            database.client:
                base_uri: '%env(resolve:DATABASE_SERVICE_URL)%'
            search.client:
                base_uri: '%env(resolve:SEARCH_SERVICE_URL)%'
            collection.client:
                base_uri: '%env(resolve:COLLECTION_SERVICE_URL)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: '%env(REDIS_URL)%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file
